---
services: docker

install:
  - bundle install
  - ansible-galaxy install --roles-path ./roles/ geerlingguy.redis
  - ansible-galaxy install --roles-path ./roles/ andrewrothstein.openresty

before_script:
  - python --version
  - ruby --version

script:
  - kitchen test