---
driver:
  name: docker

provisioner:
  name: ansible
  hosts: localhost

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/test.yml