---
driver:
  name: docker

provisioner:
  name: ansible
  hosts: localhost

platforms:
  - name: ubuntu-16.04
  - name: debian-8

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/provision.yml
      roles_path: roles
      requirements_path: requirements.yml
      ansible_vault_password_file: vault.passwd
    verifier:
      name: busser