---
dependencies:
  - role: geerlingguy.redis
    redis_requirepass: "{{ redis_password }}"
  - role: andrewrothstein.openresty
    luarocks_install:
      - luasec
      - luajson
      - lua-resty-http
      - lua-resty-redis